language: node_js
node_js:
- 6.4.0
- 6.15.1
- 7.5.0
- 7.10.1
- 8.2.1
- 8.6.0
- 8.9.4
- 9.11.2
- 10.3.0
- 10.8.0
- 10.14.2
- 11.5.0
- node
deploy:
  provider: npm
  email: stuplum@inkfish.co
  api_key:
    secure: LPvOdyX6PGBhS9WVQb/7DCQ/5ZetSXP+zo8e8miXQZKAUlsyMeBL1Jwripqd1iWHr3rOAHF27YZmd1AZTVn8JcSpEWuJ4kGwFHBgHR2JuVX1S5tLwfoPtIMdQ/x3LGh/1hpPPxIzDXBqZtDathcz3w/sbyxuiFFeNuNdNPCqpnaRiiFFJpwtJH7GBUcJdftCX9qqDar8yM8NKkzaVd4CAX5ujxCtOFtqmyiGhZv2nLwSVtwyUj+k1PkMZrmxSxEfdo1WIJbabuDv6eR8yslBQcut0Bqw5JMM1im5XENY4JC+utpjjNJpiSDmq+Zgud8t5yo5oN1gXKBud/vctNqq9GubYPrArV1p0+tRuVbteQ+QqxTMJppTSgRv2SKeGms+zcdC58KemAxvaundqEkGVrQVWYiWJakh6+Msa9fK43yoYbrT1q5qOvA0+Wxiagk/Uv7UCd6n7h+4+xyFG9z2t7gzoiafTmJQYLS+3MDb9zXjFUaPJkmfBqsay2fb9fzAgM9cBmmeUTBQVJhltNfSMkno1CcfydYmM1KSpyz6Mc8BjoQUIfdAv8wXh25HNEO6x2f11tDZ+hwfR4f9QkWA0cwhHrxS1ZfE7zaiYAGXF1cK78VJuf9NHAVwOYj75j6Zr03KTU4bv93eOf6c9Xat0kMbHu8k3phHmLeS9BN8feY=
  on:
    tags: true
    repo: stuplum/chai-mongo-doc
